name: flutter_osm_plugin_example
description: Demonstrates how to use the flutter_osm_plugin plugin.
publish_to: 'none'

environment:
  sdk: ">=3.5.2 <4.0.0"
  flutter: ">=3.24.2"
dependencies:
  flutter:
    sdk: flutter
  flutter_osm_plugin: #1.2.0 #^0.40.3+2
    path: ../
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter_hooks: ^0.18.5+1
  #osm_flutter_hooks: ^1.4.0
  pointer_interceptor: ^0.10.1+2
  routing_client_dart: ^0.5.5
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
    # permission_handler_html: 0.1.3+2
    # url_launcher_web: 2.3.3
    # web: 1.0.0
    #flutter_osm_plugin: #^0.70.3
    #  path: ../
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - asset/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
