// AUTO GENERATED BY JNIGEN 0.17.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `hamza.dali.flutter_osm_plugin.jni.OsmAndroidBridge`
extension type OsmAndroidBridge._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
      r'hamza/dali/flutter_osm_plugin/jni/OsmAndroidBridge');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<OsmAndroidBridge> type = $OsmAndroidBridge$Type$();
  static final _id_new$ = _class.constructorId(
    r'()V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory OsmAndroidBridge() {
    final _$$classRef = _class.reference;
    return _new$(_$$classRef.pointer, _id_new$.pointer)
        .object<OsmAndroidBridge>();
  }
}

extension OsmAndroidBridge$$Methods on OsmAndroidBridge {
  static final _id_ping = OsmAndroidBridge._class.instanceMethodId(
    r'ping',
    r'()Ljava/lang/String;',
  );

  static final _ping = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public fun ping(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString ping() {
    final _$$selfRef = reference;
    return _ping(_$$selfRef.pointer, _id_ping.pointer).object<jni$_.JString>();
  }

  static final _id_add = OsmAndroidBridge._class.instanceMethodId(
    r'add',
    r'(II)I',
  );

  static final _add = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>)>>(
          'globalEnv_CallIntMethod')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, core$_.int, core$_.int)>();

  /// from: `public fun add(left: kotlin.Int, right: kotlin.Int): kotlin.Int`
  core$_.int add(
    core$_.int i,
    core$_.int i1,
  ) {
    final _$$selfRef = reference;
    return _add(_$$selfRef.pointer, _id_add.pointer, i, i1).integer;
  }

  static final _id_currentThreadName = OsmAndroidBridge._class.instanceMethodId(
    r'currentThreadName',
    r'()Ljava/lang/String;',
  );

  static final _currentThreadName = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public fun currentThreadName(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString currentThreadName() {
    final _$$selfRef = reference;
    return _currentThreadName(_$$selfRef.pointer, _id_currentThreadName.pointer)
        .object<jni$_.JString>();
  }

  static final _id_get$isMainThread = OsmAndroidBridge._class.instanceMethodId(
    r'isMainThread',
    r'()Z',
  );

  static final _get$isMainThread = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public fun isMainThread(): kotlin.Boolean`
  core$_.bool get isMainThread {
    final _$$selfRef = reference;
    return _get$isMainThread(_$$selfRef.pointer, _id_get$isMainThread.pointer)
        .boolean;
  }

  static final _id_attach = OsmAndroidBridge._class.instanceMethodId(
    r'attach',
    r'(I)Z',
  );

  static final _attach = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_
                      .VarArgs<(jni$_.Int32,)>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, core$_.int)>();

  /// from: `public fun attach(viewId: kotlin.Int): kotlin.Boolean`
  core$_.bool attach(
    core$_.int i,
  ) {
    final _$$selfRef = reference;
    return _attach(_$$selfRef.pointer, _id_attach.pointer, i).boolean;
  }

  static final _id_initialize = OsmAndroidBridge._class.instanceMethodId(
    r'initialize',
    r'(IDDLjava/lang/String;)Z',
  );

  static final _initialize = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Double,
                        jni$_.Double,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.double,
              core$_.double,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun initialize(viewId: kotlin.Int, latitude: kotlin.Double, longitude: kotlin.Double, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool initialize(
    core$_.int i,
    core$_.double d,
    core$_.double d1,
    jni$_.JString string,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _initialize(_$$selfRef.pointer, _id_initialize.pointer, i, d, d1,
            _$string.pointer)
        .boolean;
  }

  static final _id_moveTo = OsmAndroidBridge._class.instanceMethodId(
    r'moveTo',
    r'(IDDZLjava/lang/String;)Z',
  );

  static final _moveTo = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Double,
                        jni$_.Double,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.double,
              core$_.double,
              core$_.int,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun moveTo(viewId: kotlin.Int, latitude: kotlin.Double, longitude: kotlin.Double, animated: kotlin.Boolean, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool moveTo(
    core$_.int i,
    core$_.double d,
    core$_.double d1,
    core$_.bool z,
    jni$_.JString string,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _moveTo(_$$selfRef.pointer, _id_moveTo.pointer, i, d, d1, z ? 1 : 0,
            _$string.pointer)
        .boolean;
  }

  static final _id_setZoom = OsmAndroidBridge._class.instanceMethodId(
    r'setZoom',
    r'(IDLjava/lang/String;)Z',
  );

  static final _setZoom = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Double,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.double,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun setZoom(viewId: kotlin.Int, zoom: kotlin.Double, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool setZoom(
    core$_.int i,
    core$_.double d,
    jni$_.JString string,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _setZoom(
            _$$selfRef.pointer, _id_setZoom.pointer, i, d, _$string.pointer)
        .boolean;
  }

  static final _id_getZoom = OsmAndroidBridge._class.instanceMethodId(
    r'getZoom',
    r'(I)D',
  );

  static final _getZoom = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<(jni$_.Int32,)>)>>('globalEnv_CallDoubleMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, core$_.int)>();

  /// from: `public fun getZoom(viewId: kotlin.Int): kotlin.Double`
  core$_.double getZoom(
    core$_.int i,
  ) {
    final _$$selfRef = reference;
    return _getZoom(_$$selfRef.pointer, _id_getZoom.pointer, i).doubleFloat;
  }

  static final _id_setRotation = OsmAndroidBridge._class.instanceMethodId(
    r'setRotation',
    r'(IDZLjava/lang/String;)Z',
  );

  static final _setRotation = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Double,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.double,
              core$_.int,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun setRotation(viewId: kotlin.Int, angle: kotlin.Double, animated: kotlin.Boolean, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool setRotation(
    core$_.int i,
    core$_.double d,
    core$_.bool z,
    jni$_.JString string,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _setRotation(_$$selfRef.pointer, _id_setRotation.pointer, i, d,
            z ? 1 : 0, _$string.pointer)
        .boolean;
  }

  static final _id_addMarker = OsmAndroidBridge._class.instanceMethodId(
    r'addMarker',
    r'(ILjava/lang/String;DDLjava/lang/String;)Z',
  );

  static final _addMarker = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Double,
                        jni$_.Double,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              core$_.double,
              core$_.double,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun addMarker(viewId: kotlin.Int, markerId: kotlin.String, latitude: kotlin.Double, longitude: kotlin.Double, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool addMarker(
    core$_.int i,
    jni$_.JString string,
    core$_.double d,
    core$_.double d1,
    jni$_.JString string1,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    return _addMarker(_$$selfRef.pointer, _id_addMarker.pointer, i,
            _$string.pointer, d, d1, _$string1.pointer)
        .boolean;
  }

  static final _id_removeMarker = OsmAndroidBridge._class.instanceMethodId(
    r'removeMarker',
    r'(ILjava/lang/String;Ljava/lang/String;)Z',
  );

  static final _removeMarker = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun removeMarker(viewId: kotlin.Int, markerId: kotlin.String, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool removeMarker(
    core$_.int i,
    jni$_.JString string,
    jni$_.JString string1,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    return _removeMarker(_$$selfRef.pointer, _id_removeMarker.pointer, i,
            _$string.pointer, _$string1.pointer)
        .boolean;
  }

  static final _id_close = OsmAndroidBridge._class.instanceMethodId(
    r'close',
    r'(I)Z',
  );

  static final _close = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_
                      .VarArgs<(jni$_.Int32,)>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, core$_.int)>();

  /// from: `public fun close(viewId: kotlin.Int): kotlin.Boolean`
  core$_.bool close(
    core$_.int i,
  ) {
    final _$$selfRef = reference;
    return _close(_$$selfRef.pointer, _id_close.pointer, i).boolean;
  }
}

final class $OsmAndroidBridge$Type$ extends jni$_.JType<OsmAndroidBridge> {
  @jni$_.internal
  const $OsmAndroidBridge$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lhamza/dali/flutter_osm_plugin/jni/OsmAndroidBridge;';
}
