// AUTO GENERATED BY JNIGEN 0.17.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `hamza.dali.flutter_osm_plugin.jni.OsmAndroidBridge`
extension type OsmAndroidBridge._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
      r'hamza/dali/flutter_osm_plugin/jni/OsmAndroidBridge');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<OsmAndroidBridge> type = $OsmAndroidBridge$Type$();
  static final _id_new$ = _class.constructorId(
    r'()V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory OsmAndroidBridge() {
    final _$$classRef = _class.reference;
    return _new$(_$$classRef.pointer, _id_new$.pointer)
        .object<OsmAndroidBridge>();
  }
}

extension OsmAndroidBridge$$Methods on OsmAndroidBridge {
  static final _id_ping = OsmAndroidBridge._class.instanceMethodId(
    r'ping',
    r'()Ljava/lang/String;',
  );

  static final _ping = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public fun ping(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString ping() {
    final _$$selfRef = reference;
    return _ping(_$$selfRef.pointer, _id_ping.pointer).object<jni$_.JString>();
  }

  static final _id_add = OsmAndroidBridge._class.instanceMethodId(
    r'add',
    r'(II)I',
  );

  static final _add = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>)>>(
          'globalEnv_CallIntMethod')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, core$_.int, core$_.int)>();

  /// from: `public fun add(left: kotlin.Int, right: kotlin.Int): kotlin.Int`
  core$_.int add(
    core$_.int i,
    core$_.int i1,
  ) {
    final _$$selfRef = reference;
    return _add(_$$selfRef.pointer, _id_add.pointer, i, i1).integer;
  }

  static final _id_currentThreadName = OsmAndroidBridge._class.instanceMethodId(
    r'currentThreadName',
    r'()Ljava/lang/String;',
  );

  static final _currentThreadName = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public fun currentThreadName(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString currentThreadName() {
    final _$$selfRef = reference;
    return _currentThreadName(_$$selfRef.pointer, _id_currentThreadName.pointer)
        .object<jni$_.JString>();
  }

  static final _id_get$isMainThread = OsmAndroidBridge._class.instanceMethodId(
    r'isMainThread',
    r'()Z',
  );

  static final _get$isMainThread = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public fun isMainThread(): kotlin.Boolean`
  core$_.bool get isMainThread {
    final _$$selfRef = reference;
    return _get$isMainThread(_$$selfRef.pointer, _id_get$isMainThread.pointer)
        .boolean;
  }
}

final class $OsmAndroidBridge$Type$ extends jni$_.JType<OsmAndroidBridge> {
  @jni$_.internal
  const $OsmAndroidBridge$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lhamza/dali/flutter_osm_plugin/jni/OsmAndroidBridge;';
}
