// AUTO GENERATED BY JNIGEN 0.17.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `hamza.dali.flutter_osm_plugin.jni.OsmAndroidBridge`
extension type OsmAndroidBridge._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
      r'hamza/dali/flutter_osm_plugin/jni/OsmAndroidBridge');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<OsmAndroidBridge> type = $OsmAndroidBridge$Type$();
  static final _id_new$ = _class.constructorId(
    r'()V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory OsmAndroidBridge() {
    final _$$classRef = _class.reference;
    return _new$(_$$classRef.pointer, _id_new$.pointer)
        .object<OsmAndroidBridge>();
  }
}

extension OsmAndroidBridge$$Methods on OsmAndroidBridge {
  static final _id_ping = OsmAndroidBridge._class.instanceMethodId(
    r'ping',
    r'()Ljava/lang/String;',
  );

  static final _ping = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public fun ping(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString ping() {
    final _$$selfRef = reference;
    return _ping(_$$selfRef.pointer, _id_ping.pointer).object<jni$_.JString>();
  }

  static final _id_add = OsmAndroidBridge._class.instanceMethodId(
    r'add',
    r'(II)I',
  );

  static final _add = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>)>>(
          'globalEnv_CallIntMethod')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, core$_.int, core$_.int)>();

  /// from: `public fun add(left: kotlin.Int, right: kotlin.Int): kotlin.Int`
  core$_.int add(
    core$_.int i,
    core$_.int i1,
  ) {
    final _$$selfRef = reference;
    return _add(_$$selfRef.pointer, _id_add.pointer, i, i1).integer;
  }

  static final _id_currentThreadName = OsmAndroidBridge._class.instanceMethodId(
    r'currentThreadName',
    r'()Ljava/lang/String;',
  );

  static final _currentThreadName = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public fun currentThreadName(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString currentThreadName() {
    final _$$selfRef = reference;
    return _currentThreadName(_$$selfRef.pointer, _id_currentThreadName.pointer)
        .object<jni$_.JString>();
  }

  static final _id_get$isMainThread = OsmAndroidBridge._class.instanceMethodId(
    r'isMainThread',
    r'()Z',
  );

  static final _get$isMainThread = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public fun isMainThread(): kotlin.Boolean`
  core$_.bool get isMainThread {
    final _$$selfRef = reference;
    return _get$isMainThread(_$$selfRef.pointer, _id_get$isMainThread.pointer)
        .boolean;
  }

  static final _id_attach = OsmAndroidBridge._class.instanceMethodId(
    r'attach',
    r'(I)Z',
  );

  static final _attach = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_
                      .VarArgs<(jni$_.Int32,)>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, core$_.int)>();

  /// from: `public fun attach(viewId: kotlin.Int): kotlin.Boolean`
  core$_.bool attach(
    core$_.int i,
  ) {
    final _$$selfRef = reference;
    return _attach(_$$selfRef.pointer, _id_attach.pointer, i).boolean;
  }

  static final _id_initialize = OsmAndroidBridge._class.instanceMethodId(
    r'initialize',
    r'(IDDLjava/lang/String;)Z',
  );

  static final _initialize = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Double,
                        jni$_.Double,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.double,
              core$_.double,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun initialize(viewId: kotlin.Int, latitude: kotlin.Double, longitude: kotlin.Double, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool initialize(
    core$_.int i,
    core$_.double d,
    core$_.double d1,
    jni$_.JString string,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _initialize(_$$selfRef.pointer, _id_initialize.pointer, i, d, d1,
            _$string.pointer)
        .boolean;
  }

  static final _id_moveTo = OsmAndroidBridge._class.instanceMethodId(
    r'moveTo',
    r'(IDDZLjava/lang/String;)Z',
  );

  static final _moveTo = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Double,
                        jni$_.Double,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.double,
              core$_.double,
              core$_.int,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun moveTo(viewId: kotlin.Int, latitude: kotlin.Double, longitude: kotlin.Double, animated: kotlin.Boolean, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool moveTo(
    core$_.int i,
    core$_.double d,
    core$_.double d1,
    core$_.bool z,
    jni$_.JString string,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _moveTo(_$$selfRef.pointer, _id_moveTo.pointer, i, d, d1, z ? 1 : 0,
            _$string.pointer)
        .boolean;
  }

  static final _id_setZoom = OsmAndroidBridge._class.instanceMethodId(
    r'setZoom',
    r'(IDLjava/lang/String;)Z',
  );

  static final _setZoom = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Double,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.double,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun setZoom(viewId: kotlin.Int, zoom: kotlin.Double, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool setZoom(
    core$_.int i,
    core$_.double d,
    jni$_.JString string,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _setZoom(
            _$$selfRef.pointer, _id_setZoom.pointer, i, d, _$string.pointer)
        .boolean;
  }

  static final _id_getZoom = OsmAndroidBridge._class.instanceMethodId(
    r'getZoom',
    r'(I)D',
  );

  static final _getZoom = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<(jni$_.Int32,)>)>>('globalEnv_CallDoubleMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, core$_.int)>();

  /// from: `public fun getZoom(viewId: kotlin.Int): kotlin.Double`
  core$_.double getZoom(
    core$_.int i,
  ) {
    final _$$selfRef = reference;
    return _getZoom(_$$selfRef.pointer, _id_getZoom.pointer, i).doubleFloat;
  }

  static final _id_setRotation = OsmAndroidBridge._class.instanceMethodId(
    r'setRotation',
    r'(IDZLjava/lang/String;)Z',
  );

  static final _setRotation = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Double,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.double,
              core$_.int,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun setRotation(viewId: kotlin.Int, angle: kotlin.Double, animated: kotlin.Boolean, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool setRotation(
    core$_.int i,
    core$_.double d,
    core$_.bool z,
    jni$_.JString string,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _setRotation(_$$selfRef.pointer, _id_setRotation.pointer, i, d,
            z ? 1 : 0, _$string.pointer)
        .boolean;
  }

  static final _id_addMarker = OsmAndroidBridge._class.instanceMethodId(
    r'addMarker',
    r'(ILjava/lang/String;DD[BLjava/lang/String;)Z',
  );

  static final _addMarker = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Double,
                        jni$_.Double,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              core$_.double,
              core$_.double,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun addMarker(viewId: kotlin.Int, markerId: kotlin.String, latitude: kotlin.Double, longitude: kotlin.Double, icon: kotlin.ByteArray?, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool addMarker(
    core$_.int i,
    jni$_.JString string,
    core$_.double d,
    core$_.double d1,
    jni$_.JByteArray? bs,
    jni$_.JString string1,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$bs = bs?.reference ?? jni$_.jNullReference;
    final _$string1 = string1.reference;
    return _addMarker(_$$selfRef.pointer, _id_addMarker.pointer, i,
            _$string.pointer, d, d1, _$bs.pointer, _$string1.pointer)
        .boolean;
  }

  static final _id_addMarkers = OsmAndroidBridge._class.instanceMethodId(
    r'addMarkers',
    r'(I[Ljava/lang/String;[DLjava/lang/String;)Z',
  );

  static final _addMarkers = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun addMarkers(viewId: kotlin.Int, markerIds: kotlin.Array<kotlin.String>, coordinates: kotlin.DoubleArray, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool addMarkers(
    core$_.int i,
    jni$_.JArray<jni$_.JString> strings,
    jni$_.JDoubleArray ds,
    jni$_.JString string,
  ) {
    final _$$selfRef = reference;
    final _$strings = strings.reference;
    final _$ds = ds.reference;
    final _$string = string.reference;
    return _addMarkers(_$$selfRef.pointer, _id_addMarkers.pointer, i,
            _$strings.pointer, _$ds.pointer, _$string.pointer)
        .boolean;
  }

  static final _id_updateMarkerIcon = OsmAndroidBridge._class.instanceMethodId(
    r'updateMarkerIcon',
    r'(ILjava/lang/String;[BLjava/lang/String;)Z',
  );

  static final _updateMarkerIcon = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun updateMarkerIcon(viewId: kotlin.Int, markerId: kotlin.String, icon: kotlin.ByteArray, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool updateMarkerIcon(
    core$_.int i,
    jni$_.JString string,
    jni$_.JByteArray bs,
    jni$_.JString string1,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$bs = bs.reference;
    final _$string1 = string1.reference;
    return _updateMarkerIcon(_$$selfRef.pointer, _id_updateMarkerIcon.pointer,
            i, _$string.pointer, _$bs.pointer, _$string1.pointer)
        .boolean;
  }

  static final _id_removeMarker = OsmAndroidBridge._class.instanceMethodId(
    r'removeMarker',
    r'(ILjava/lang/String;Ljava/lang/String;)Z',
  );

  static final _removeMarker = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun removeMarker(viewId: kotlin.Int, markerId: kotlin.String, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool removeMarker(
    core$_.int i,
    jni$_.JString string,
    jni$_.JString string1,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    return _removeMarker(_$$selfRef.pointer, _id_removeMarker.pointer, i,
            _$string.pointer, _$string1.pointer)
        .boolean;
  }

  static final _id_removeMarkers = OsmAndroidBridge._class.instanceMethodId(
    r'removeMarkers',
    r'(I[Ljava/lang/String;Ljava/lang/String;)Z',
  );

  static final _removeMarkers = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun removeMarkers(viewId: kotlin.Int, markerIds: kotlin.Array<kotlin.String>, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool removeMarkers(
    core$_.int i,
    jni$_.JArray<jni$_.JString> strings,
    jni$_.JString string,
  ) {
    final _$$selfRef = reference;
    final _$strings = strings.reference;
    final _$string = string.reference;
    return _removeMarkers(_$$selfRef.pointer, _id_removeMarkers.pointer, i,
            _$strings.pointer, _$string.pointer)
        .boolean;
  }

  static final _id_addCircle = OsmAndroidBridge._class.instanceMethodId(
    r'addCircle',
    r'(ILjava/lang/String;DDDIIDLjava/lang/String;)Z',
  );

  static final _addCircle = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Double,
                        jni$_.Double,
                        jni$_.Double,
                        jni$_.Int32,
                        jni$_.Int32,
                        jni$_.Double,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              core$_.double,
              core$_.double,
              core$_.double,
              core$_.int,
              core$_.int,
              core$_.double,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun addCircle(viewId: kotlin.Int, shapeId: kotlin.String, latitude: kotlin.Double, longitude: kotlin.Double, radius: kotlin.Double, fillColor: kotlin.Int, borderColor: kotlin.Int, strokeWidth: kotlin.Double, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool addCircle(
    core$_.int i,
    jni$_.JString string,
    core$_.double d,
    core$_.double d1,
    core$_.double d2,
    core$_.int i1,
    core$_.int i2,
    core$_.double d3,
    jni$_.JString string1,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    return _addCircle(_$$selfRef.pointer, _id_addCircle.pointer, i,
            _$string.pointer, d, d1, d2, i1, i2, d3, _$string1.pointer)
        .boolean;
  }

  static final _id_addRectangle = OsmAndroidBridge._class.instanceMethodId(
    r'addRectangle',
    r'(ILjava/lang/String;DDDIIDLjava/lang/String;)Z',
  );

  static final _addRectangle = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Double,
                        jni$_.Double,
                        jni$_.Double,
                        jni$_.Int32,
                        jni$_.Int32,
                        jni$_.Double,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              core$_.double,
              core$_.double,
              core$_.double,
              core$_.int,
              core$_.int,
              core$_.double,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun addRectangle(viewId: kotlin.Int, shapeId: kotlin.String, latitude: kotlin.Double, longitude: kotlin.Double, distance: kotlin.Double, fillColor: kotlin.Int, borderColor: kotlin.Int, strokeWidth: kotlin.Double, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool addRectangle(
    core$_.int i,
    jni$_.JString string,
    core$_.double d,
    core$_.double d1,
    core$_.double d2,
    core$_.int i1,
    core$_.int i2,
    core$_.double d3,
    jni$_.JString string1,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    return _addRectangle(_$$selfRef.pointer, _id_addRectangle.pointer, i,
            _$string.pointer, d, d1, d2, i1, i2, d3, _$string1.pointer)
        .boolean;
  }

  static final _id_removeShape = OsmAndroidBridge._class.instanceMethodId(
    r'removeShape',
    r'(ILjava/lang/String;Ljava/lang/String;)Z',
  );

  static final _removeShape = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun removeShape(viewId: kotlin.Int, shapeId: kotlin.String, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool removeShape(
    core$_.int i,
    jni$_.JString string,
    jni$_.JString string1,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    return _removeShape(_$$selfRef.pointer, _id_removeShape.pointer, i,
            _$string.pointer, _$string1.pointer)
        .boolean;
  }

  static final _id_clearShapes = OsmAndroidBridge._class.instanceMethodId(
    r'clearShapes',
    r'(ILjava/lang/String;)Z',
  );

  static final _clearShapes = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Int32, jni$_.Pointer<jni$_.Void>)>)>>(
          'globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, core$_.int, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun clearShapes(viewId: kotlin.Int, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool clearShapes(
    core$_.int i,
    jni$_.JString string,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _clearShapes(
            _$$selfRef.pointer, _id_clearShapes.pointer, i, _$string.pointer)
        .boolean;
  }

  static final _id_setStaticPositions =
      OsmAndroidBridge._class.instanceMethodId(
    r'setStaticPositions',
    r'(ILjava/lang/String;[D[BLjava/lang/String;)Z',
  );

  static final _setStaticPositions = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun setStaticPositions(viewId: kotlin.Int, groupId: kotlin.String, coordinates: kotlin.DoubleArray, icon: kotlin.ByteArray?, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool setStaticPositions(
    core$_.int i,
    jni$_.JString string,
    jni$_.JDoubleArray ds,
    jni$_.JByteArray? bs,
    jni$_.JString string1,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$ds = ds.reference;
    final _$bs = bs?.reference ?? jni$_.jNullReference;
    final _$string1 = string1.reference;
    return _setStaticPositions(
            _$$selfRef.pointer,
            _id_setStaticPositions.pointer,
            i,
            _$string.pointer,
            _$ds.pointer,
            _$bs.pointer,
            _$string1.pointer)
        .boolean;
  }

  static final _id_removeStaticPositions =
      OsmAndroidBridge._class.instanceMethodId(
    r'removeStaticPositions',
    r'(ILjava/lang/String;Ljava/lang/String;)Z',
  );

  static final _removeStaticPositions = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun removeStaticPositions(viewId: kotlin.Int, groupId: kotlin.String, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool removeStaticPositions(
    core$_.int i,
    jni$_.JString string,
    jni$_.JString string1,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    return _removeStaticPositions(
            _$$selfRef.pointer,
            _id_removeStaticPositions.pointer,
            i,
            _$string.pointer,
            _$string1.pointer)
        .boolean;
  }

  static final _id_drawRoad = OsmAndroidBridge._class.instanceMethodId(
    r'drawRoad',
    r'(ILjava/lang/String;[DIDIDZZLjava/lang/String;)Z',
  );

  static final _drawRoad = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Double,
                        jni$_.Int32,
                        jni$_.Double,
                        jni$_.Int32,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.double,
              core$_.int,
              core$_.double,
              core$_.int,
              core$_.int,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun drawRoad(viewId: kotlin.Int, roadId: kotlin.String, coordinates: kotlin.DoubleArray, roadColor: kotlin.Int, roadWidth: kotlin.Double, borderColor: kotlin.Int, borderWidth: kotlin.Double, zoomInto: kotlin.Boolean, dotted: kotlin.Boolean, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool drawRoad(
    core$_.int i,
    jni$_.JString string,
    jni$_.JDoubleArray ds,
    core$_.int i1,
    core$_.double d,
    core$_.int i2,
    core$_.double d1,
    core$_.bool z,
    core$_.bool z1,
    jni$_.JString string1,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$ds = ds.reference;
    final _$string1 = string1.reference;
    return _drawRoad(
            _$$selfRef.pointer,
            _id_drawRoad.pointer,
            i,
            _$string.pointer,
            _$ds.pointer,
            i1,
            d,
            i2,
            d1,
            z ? 1 : 0,
            z1 ? 1 : 0,
            _$string1.pointer)
        .boolean;
  }

  static final _id_removeRoad = OsmAndroidBridge._class.instanceMethodId(
    r'removeRoad',
    r'(ILjava/lang/String;Ljava/lang/String;)Z',
  );

  static final _removeRoad = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun removeRoad(viewId: kotlin.Int, roadId: kotlin.String, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool removeRoad(
    core$_.int i,
    jni$_.JString string,
    jni$_.JString string1,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    return _removeRoad(_$$selfRef.pointer, _id_removeRoad.pointer, i,
            _$string.pointer, _$string1.pointer)
        .boolean;
  }

  static final _id_clearRoads = OsmAndroidBridge._class.instanceMethodId(
    r'clearRoads',
    r'(ILjava/lang/String;)Z',
  );

  static final _clearRoads = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Int32, jni$_.Pointer<jni$_.Void>)>)>>(
          'globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, core$_.int, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun clearRoads(viewId: kotlin.Int, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool clearRoads(
    core$_.int i,
    jni$_.JString string,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _clearRoads(
            _$$selfRef.pointer, _id_clearRoads.pointer, i, _$string.pointer)
        .boolean;
  }

  static final _id_setRasterTile = OsmAndroidBridge._class.instanceMethodId(
    r'setRasterTile',
    r'(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z',
  );

  static final _setRasterTile = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun setRasterTile(viewId: kotlin.Int, url: kotlin.String, sourceName: kotlin.String, tileExtension: kotlin.String, minZoom: kotlin.Int, maxZoom: kotlin.Int, apiKey: kotlin.String, apiValue: kotlin.String, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool setRasterTile(
    core$_.int i,
    jni$_.JString string,
    jni$_.JString string1,
    jni$_.JString string2,
    core$_.int i1,
    core$_.int i2,
    jni$_.JString string3,
    jni$_.JString string4,
    jni$_.JString string5,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    final _$string3 = string3.reference;
    final _$string4 = string4.reference;
    final _$string5 = string5.reference;
    return _setRasterTile(
            _$$selfRef.pointer,
            _id_setRasterTile.pointer,
            i,
            _$string.pointer,
            _$string1.pointer,
            _$string2.pointer,
            i1,
            i2,
            _$string3.pointer,
            _$string4.pointer,
            _$string5.pointer)
        .boolean;
  }

  static final _id_setVectorTile = OsmAndroidBridge._class.instanceMethodId(
    r'setVectorTile',
    r'(ILjava/lang/String;Ljava/lang/String;IILjava/lang/String;)Z',
  );

  static final _setVectorTile = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun setVectorTile(viewId: kotlin.Int, styleUrl: kotlin.String, sourceName: kotlin.String, minZoom: kotlin.Int, maxZoom: kotlin.Int, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool setVectorTile(
    core$_.int i,
    jni$_.JString string,
    jni$_.JString string1,
    core$_.int i1,
    core$_.int i2,
    jni$_.JString string2,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    final _$string1 = string1.reference;
    final _$string2 = string2.reference;
    return _setVectorTile(_$$selfRef.pointer, _id_setVectorTile.pointer, i,
            _$string.pointer, _$string1.pointer, i1, i2, _$string2.pointer)
        .boolean;
  }

  static final _id_resetTile = OsmAndroidBridge._class.instanceMethodId(
    r'resetTile',
    r'(ILjava/lang/String;)Z',
  );

  static final _resetTile = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Int32, jni$_.Pointer<jni$_.Void>)>)>>(
          'globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, core$_.int, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun resetTile(viewId: kotlin.Int, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool resetTile(
    core$_.int i,
    jni$_.JString string,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _resetTile(
            _$$selfRef.pointer, _id_resetTile.pointer, i, _$string.pointer)
        .boolean;
  }

  static final _id_setOverlaysVisible =
      OsmAndroidBridge._class.instanceMethodId(
    r'setOverlaysVisible',
    r'(IZLjava/lang/String;)Z',
  );

  static final _setOverlaysVisible = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun setOverlaysVisible(viewId: kotlin.Int, visible: kotlin.Boolean, requestId: kotlin.String): kotlin.Boolean`
  core$_.bool setOverlaysVisible(
    core$_.int i,
    core$_.bool z,
    jni$_.JString string,
  ) {
    final _$$selfRef = reference;
    final _$string = string.reference;
    return _setOverlaysVisible(_$$selfRef.pointer,
            _id_setOverlaysVisible.pointer, i, z ? 1 : 0, _$string.pointer)
        .boolean;
  }

  static final _id_close = OsmAndroidBridge._class.instanceMethodId(
    r'close',
    r'(I)Z',
  );

  static final _close = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_
                      .VarArgs<(jni$_.Int32,)>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, core$_.int)>();

  /// from: `public fun close(viewId: kotlin.Int): kotlin.Boolean`
  core$_.bool close(
    core$_.int i,
  ) {
    final _$$selfRef = reference;
    return _close(_$$selfRef.pointer, _id_close.pointer, i).boolean;
  }
}

final class $OsmAndroidBridge$Type$ extends jni$_.JType<OsmAndroidBridge> {
  @jni$_.internal
  const $OsmAndroidBridge$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lhamza/dali/flutter_osm_plugin/jni/OsmAndroidBridge;';
}
